# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

 branches:
   include:
     - main

pool:
  name: 'SelfHostedVM'

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure PayAsYouGo (90f2a80e-6934-46d8-9b29-95402af7c21c)'
    command: 'test'
    projects: '*/Functions.Tests.csproj'
    testRunTitle: 'UnitTests'
    requestTimeout: 3000
- task: CopyFiles@2
  inputs:
    SourceFolder: '.' #copy everything from the root folder
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStaggingDirectory)' #save it in a temprory directory before publishing as an artifact
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStaggingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
